# Generated by Django 5.2 on 2026-04-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'platform'], name='users_devic_user_id_2cd522_idx'),
        ),
    ]
