# Generated by Django 5.2 on 2026-04-25 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
        ('users', '0002_device_users_devic_user_id_2cd522_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='platforms.platform'),
        ),
    ]
